### ISSUE TITLE
Looking to update notes to approver field

### ISSUE THREAD

**Issue by TestinProd123** [AvePoint/cloud-governance-client#10]
Hi there, I'm currently building a solution that assesses guest requests and validates them externally. Part of this is either approving using the task approval call POST /tasks/{id}/approve or reassigning the task POST /tasks/{id}/reassignto/{user}.

I would like to add a message detailing what has happened behind the scenes in assessing the request to the "Notes to approvers" field programmatically, could you please advise how I could go about doing this?

**Comment by sear-lin-avepoint** [comment]
Hi @TestinProd123 

you can firstly use the get request api GET /requests/createguestuser/{id} to get the request, and modify the "Notes to approvers" field, then update the request using the update request api POST /tasks/{id}/createguestuser

**Comment by TestinProd123** [comment]
I see so the first GET request you have mentioned targets the request which may contain multiple tasks. 
The second POST request seems to be targeted to the specific task under that request with {id} reflecting the Task ID. If I try to hit this with a POST request updating the notesToAppover field I get The remote server returned an error: (405) Method Not Allowed. Is there a different field I should be trying to update against the task?

**Comment by TestinProd123** [comment]
AH looking at your documentation this should be a PUT request?

**Comment by sear-lin-avepoint** [comment]
@TestinProd123 
sorry, the second api is PUT instead of POST
you can choose the task that you reassigned to , the task id is just for notification purpose, it will update the request anyway.

**Comment by TestinProd123** [comment]
> @TestinProd123 sorry, the second api is PUT instead of POST you can choose the task that you reassigned to , the task id is just for notification purpose, it will update the request anyway.

Ah okay so to confirm with PUT /tasks/{id}/createguestuser is the ID the request ID?
What should the body be structured like for the PUT request?  Presume just get the JSON output of the GET request, edit the notesToApprovers and use this as the body?

**Comment by sear-lin-avepoint** [comment]
@TestinProd123 
PUT /tasks/{id}/createguestuser, the id is the task id, and yes, the body is the JSON output of the GET request
