### ISSUE TITLE
Cloud Api Backup Job

### ISSUE THREAD

**Issue by baartho** [AvePoint/cloud-governance-client#11]
Hey guys,

First of all I'm sorry for posting on the incorrect GitHub project but I couldn't find the appropriate one.

I'm using the AvePoint.AOS.Public.SDK to retrieve backup jobs informations. Right now I'm collecting successfully the State, StartTime, Duration, FailedCount, SuccessfulCount.

var context = AosApi.GetContext(AOSPlatform.Global, "usr", "pw");
var records = context.CloudBackupService.GetJobs(new Aos.Sdk.Models.CloudBackup.JobFilter());

The issue is that I also need additional fields/info which are: The clients, backupsize, retention time. Is there another API endpoint / or perhaps even another API which I can gather these missing fields?

Thank you

**Comment by sear-lin-avepoint** [comment]
Hi @baartho 
We need more clarification about your requirements, some of them may haven't been supported yet, could you please submit a AvePoint support ticket for us, then we will contact you.

**Comment by baartho** [comment]
Hi @sear-lin-avepoint,

I've already. Tickets: C-13512018-H9V6, C-13512131-Z4B3.

Thank you!!
