### ISSUE TITLE
Started request waits wrongly for approval

### ISSUE THREAD

**Issue by MarkusFeldmann** [AvePoint/cloud-governance-client#6]
Hi, I just ran into another issue.
When I start a service that changes admins for a site (the corresponding service in the portal is set to 'auto-approval') it gets stuck and waits for approval, but there is no 'approve button' and when I click 'skip' it fails,

I tried to achieve this by trying to use this:
var myService = serviceAPI.GetCustomService(serviceId);
var template = myService.RequestTemplate;  // This always results in null, how can I get a valid RequestTemplate?

Since this did not work, I uses the following code (it runs, but with the approval problem stated above):

try
            {
                //get a ref to 'Site Einstellungen anpassen', 7cb6fdc7-81dd-4c80-a880-7d94918251d1
                ServiceListPageResult result = srvApi.GetMyServices("Site Einstellungen anpassen");
                var serviceRequest = srvApi.GetChangeSiteContactService(result.Value[0].Id);
                var request = serviceRequest.RequestTemplate;
                List<ChangeContactByUrlSetting> cburl = new();
                request.Summary = "Changing ROOT_OBJECT";                
                ChangeContactByUrlSetting cburlsetting = new ChangeContactByUrlSetting();

                List<ApiUser> addAdmins = new List<ApiUser> { new ApiUser(loginName: "...") };
                
                cburlsetting.NewSecondaryContact = new ApiUser(loginName: "...");
                cburlsetting.NewPrimaryContact = new ApiUser(loginName: "...");
                cburlsetting.NewPrimaryAdministrator = new ApiUser(loginName: "...");
                cburlsetting.NewAdditionalAdministrators = addAdmins;
                cburlsetting.SiteUrl = "https://.../sites/...";
                
                cburl.Add(cburlsetting);
                request.ChangeByUrlSetting = cburl;

                int metaIndex = request.Metadatas.FindIndex(m => m.Name == "META_ROOT_OBJECT");
                request.Metadatas[metaIndex].SingleLineOrMultipleLineValue = "TESTTEST";
                var myService = requestsApi.SubmitChangeSiteContactRequest(request);

            }
            catch (ApiException e)
            {
                ...
            }
Do you have a tip how I can run custom services?

best regards,
Markus

**Comment by williamsunnnnnn** [comment]
Hi Markus,

The custom service is a type of services, it is different from change contact service, it means that you cannot get custom service with a change site contact service ID.

According to the code you provided, I think the request missed a site ID, also you should validate the site URL before submite the request to make sure the site is available. However, I think the site URL is enough for this case, I will try to submit a internal ticket to improve it.

Here is a sample for submit a change site contact request:

```
                var serviceId = this.ServicesApi.GetServiceId(data.ServiceName);
                var validateResult = this.ServicesApi.ValidateForChangeSiteContactService(serviceId,
                    new SiteValidationParameter
                    {
                        Uri = data.SiteUrl,
                    });
                var service = this.ServicesApi.GetChangeSiteContactService(serviceId);
                var request = service.RequestTemplate;
                request.ChangeByUrlSetting = new List<ChangeContactByUrlSetting>();
                var setting = new ChangeContactByUrlSetting
                {
                    SiteUrl = data.SiteUrl,
                    SiteId = validateResult.SiteId,
                    NewPrimaryContact = validateResult.PrimaryContact,
                    NewSecondaryContact = validateResult.SecondaryContact,
                    NewPrimaryAdministrator = new ApiUser { LoginName = data.PrimaryAdministratorLoginName },
                    NewAdditionalAdministrators = validateResult.AdditionalAdministrators
                };
                request.ChangeByUrlSetting.Add(setting);
                request.Summary = $"Api_Sample_ChangeSCAdminByUrl_Request_{DateTime.Now}";
                return this.RequestsApi.SubmitChangeSiteContactRequest(request);
```

Best regards,

**Comment by MarkusFeldmann** [comment]
Hi William
thanks, that helped. I have one last thing that I need to do (for now). We use metadata to tie sites and teams together logically and from time to time I need to update these. Analogous to your suggestion I did the following with a changesitesettingsservise, but it complyins and does not let me send the request. We do have a metadata single line of text metadata field in the service.


try
            {
                string serviceName = "Change Site Metadata";
                var serviceId = srvApi.GetServiceId(serviceName);
                var serviceRequest = srvApi.GetChangeSiteSettingService(serviceId);

                string siteUrl = @https://sometenant.sharepoint.com/sites/somesite;
                var validateResult = srvApi.ValidateForChangeSiteSettingService(serviceId,
                    new SiteValidationParameter
                    {
                        Uri = siteUrl,
                        
                    });
                
                var request = serviceRequest.RequestTemplate;
                request.SiteUrl = validateResult.SiteUrl;                                
                request.Summary = "Changing ROOT_OBJECT";

				//tried to lookup the props here,...
                int metaIndex = validateResult.Metadatas.FindIndex(m => m.Name == "META_ROOT_OBJECT");
                var origMetadata = validateResult.Metadatas[metaIndex];
				
				
                origMetadata.SingleLineOrMultipleLineMetadataSettings.Value = "IDIDIDID";

                request.Metadatas = new List<RequestMetadata> { 
                    new RequestMetadata { 
                        Name = origMetadata.DisplayName,
                        SingleLineOrMultipleLineValue = "IDIDIDIDID",
                        DisplayName = origMetadata.Name,
                        Type = MetadataFieldType.SingleLineText,
                        Id = origMetadata.Id,
                    } };


                var myService = requestsApi.SubmitChangeSiteSettingRequest(request);

                request.Metadatas.ForEach(meta => Console.WriteLine($"{meta.Name}, {meta.ValueDisplayString}"));
            }
            catch (ApiException e)
            {
...
            }


Thanks a lot,
best regards,
Markus

**Comment by williamsunnnnnn** [comment]
Hi,

I'm not sure what is "does not let me send the request",  code cannot be built or submit failed?
But I found the RequestMetadata model doesn't have a property named DisplayName.

Please try to use code below:

  ```
 request.Metadatas = new List<RequestMetadata> {
     new RequestMetadata(name: origMetadata.Name, value: "new value", action: MetadataActionType.Edit)
 };
```

**Comment by MarkusFeldmann** [comment]
Hi William

That works, I missed to add the metadata properties in both places in the service. The request goes through now and shows the correct value in "my requests". In the workspace reports it is still not visible, I guess there is timer that collects data and it will show eventually,...

Is there somewhere a more complete documentation? It's hard to figure out how to do things if I don't know what params and values are expected. Errors often come as 'a property has not been set,...'

anyway, thanks a lot
Markus

**Comment by sear-lin-avepoint** [comment]
Hi @MarkusFeldmann 
It will show in the workspaces report until the request status is completed.

There are some examples which include most of the service types.
https://github.com/AvePoint/cloud-governance-client/tree/main/example/csharp/netframework/Requests

**Comment by williamsunnnnnn** [comment]
Hi @MarkusFeldmann ,

The metadata you typed is service metadata, please change the metadata property to ChangedMetadatas if you want to change the workspace metadata, code below:

```
request.ChangedMetadatas = new List<RequestMetadata> {
   new RequestMetadata(name: origMetadata.Name, value: "new value", action: MetadataActionType.Edit)
};
```

**Comment by MarkusFeldmann** [comment]
ok, found it in the example, added the siteId. Now it plays ball. :-)

thanks a lot for your patience and have a great week.

best regards, 
Markus
